allow:
  - basically
  - deposit
  - easy
  - execute
  - executed
  - failed
  - failure
  - failures
  - funeral
  - german
  - hooks
  - host-hostess
  - hostesses-hosts
  - invalid
  - just
  - master
  - obvious
  - of-course
  - period
  - prince-princess
  - pros
  - reject
  - remain
  - simple
  - special
  - whitespace
