name: Deploy to Azure Stage
on:
  push:
    branches: ['develop', 'feature/dx-1977_fix_stage_deploy']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build
        run: |
          docker-compose run \
            -e GITHUB_BRANCH=develop \
            -e GITHUB_REPOSITORY_URL=https://github.com/SwedbankPay/developer.swedbankpay.com \
            portal build \
            --env=production \
            --site-url=https://developer.stage.swedbankpay.com

      - name: upload site
        uses: actions/upload-artifact@v3
        with:
          name: stage-site
          path: _site

      - name: login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      - name: deploy
        uses: azure/CLI@v1.0.7
        with:
          inlineScript: az storage blob upload-batch -s _site -d "\$web" --account-name blobdevportalstage --overwrite
