name: Deploy to stage
on: 
  push:
    branches: ['develop', 'feature/*']

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - uses: actions/checkout@v1
      - name: Fetch tags and master for GitVersion
        run: |
          git fetch --tags
          git branch --create-reflog master origin/master
      - name: Install GitVersion
        uses: gittools/actions/setup-gitversion@v0.9.9
        with:
          versionSpec: '5.1.x'
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/execute-gitversion@v0.9.9
      
      - name: Build the site in the jekyll/builder container
        run: |
          docker-compose run \
            -e PAGES_REPO_NWO=${{ github.repository }} \
            -e JEKYLL_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            portal build \
            --env=production \
            --verify \
            --ignore-url http://restcookbook.com/Basics/loggingin/ \
            --ignore-url https://blogs.oracle.com/java-platform-group/jdk-8-will-use-tls-12-as-default \
            --ignore-url https://zend18.zendesk.com/hc/en-us/articles/219131697-HowTo-Implement-TLS-1-2-Support-with-the-cURL-PHP-Extension-in-Zend-Server

      - name: Azure Login
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      - name: Azure Deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch -s _site -d ${{ github.ref }} --account-name spaydevportalstoragedev --debug
