name: Test

on: [push, pull_request]

jobs:
  variables:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.variables.outputs.branch }}
      repository_url: ${{ steps.variables.outputs.repository_url }}

    steps:
      - uses: actions/checkout@v3
      - name: Generate variables
        id: variables
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: .github/scripts/variables.sh

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: docker login
        run: docker login https://docker.pkg.github.com -u SwedbankPay --password ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: docker-compose run portal build --site-url=https://developer.swedbankpay.com

      - name: Upload site
        uses: actions/upload-artifact@v3
        with:
          name: build-site
          path: _site

  verify:
    runs-on: ubuntu-latest
    needs: [variables, build]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: build-site
          path: _site

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: bundle config
        run: bundle config path vendor/bundle

      - name: bundle install
        run: bundle install --jobs 4 --retry 3

      - name: Cache HTMLProofer
        id: cache-htmlproofer
        uses: actions/cache@v3
        with:
          path: tmp/.htmlproofer
          key: ${{ runner.os }}-htmlproofer

      - name: HTMLProofer
        run: |
          bundle exec htmlproofer \
            _site \
            --assume-extension \
            --check-html \
            --enforce-https \
            --internal-domains "developer.swedbankpay.com" \
            --hydra '{ "max_concurrency": 32 }' \
            --url-ignore "https://github.com/,http://restcookbook.com/Basics/loggingin/,https://blogs.oracle.com/java-platform-group/jdk-8-will-use-tls-12-as-default,https://zend18.zendesk.com/hc/en-us/articles/219131697-HowTo-Implement-TLS-1-2-Support-with-the-cURL-PHP-Extension-in-Zend-Server"

      - name: Verify absolute URL
        run: grep 'https://developer.swedbankpay.com/' $(pwd)/_site/index.html

      - name: Verify base URL
        run: grep 'src="/assets/' $(pwd)/_site/index.html
